on: [push, pull_request]
name: dev-build
jobs:
  build:
    strategy:
      matrix:
        node-version: [12.x, 13.x, 14.x]
        platform: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Packages
      run: npm install
    - name: Check Code Quality
      run: npm run lint
    - name: Build
      run: npm run build